# Generated by Django 4.2.2 on 2023-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_articulo_foto_articulo_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil_recortada',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/fotos_perfil_recortadas'),
        ),
    ]
