# Generated by Django 4.2.2 on 2023-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_cliente_foto_perfil_recortada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto_perfil_recortada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
