# Generated by Django 4.2.2 on 2023-07-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_remove_cliente_foto_perfil_recortada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='descripcion',
            new_name='notas',
        ),
    ]
